module TaggableModelMethods
  def self.included(target)
    target.extend ClassMethods
  end
  
  module ClassMethods
    
    # paginate_tagged_with doesn't work propertly
    # http://deaddeadgood.com/2008/3/11/will_paginate-and-acts_as_taggable_on_steroids
    def paginate_tagged(tags, args = {})
      if tags.blank?
        paginate args
      else
        options = find_options_for_find_tagged_with(tags, :match_all => true)
        options.merge!(args)
        # The default count query generated by paginate includes COUNT(DISTINCT Posts.*) which errors, at least on mysql
        # Below we override the default select statement used to perform the count so that it becomes COUNT(DISTINCT Posts.id)
        paginate(options.merge(:count => { :select => options[:select].gsub('*', 'id') }))
      end
    end
    
  end

end