---
email_nightly: true
consolidate_directories: false
scan_directories: false
clear_sessions: true
clean_tmp: true
source_directory: nil
sub_directories: []
target_directory: nil
backup_mysql_local: true
mysql_local_command: "/usr/bin/mysqldump -u childsworld -pbeg8te childsworld | /bin/gzip -9 > /var/www/childsworld.com/shared/tmp/childsworld.sql.gz"
backup_mysql: true
mysql_command: "cd /var/www/childsworld.com/current && RAILS_ENV=production /usr/local/bin/backup perform --trigger childsworld --config_file /var/www/childsworld.com/current/config/backup.rb --data-path /var/www/childsworld.com/shared/backup --log-path /var/www/childsworld.com/shared/log --tmp-path /var/www/childsworld.com/shared/tmp"
rotate_logs: true
rotate_logs_command: "/var/www/childsworld.com/current/script/logrotate x /var/www/childsworld.com/current"
clear_wait_a_minute_request_logs: true
implement_price_changes: true
distribute_price_changes: true
