---
email_nightly: true
consolidate_directories: true
scan_directories: true
clear_sessions: true
clean_tmp: true
source_directory: /var/www/vhosts/cherrylakepublishing.com/web_users
sub_directories: [amnet, cg, designlab]
target_directory: /var/www/vhosts/cherrylakepublishing.com/private/ftp
backup_mysql_local: true
mysql_local_command: "/usr/bin/mysqldump -u cherrylake -pXXXX cherrylake | /bin/gzip -9 > /var/www/vhosts/cherrylakepublishing.com/shared/tmp/cherrylake.sql.gz"
backup_mysql: true
mysql_command: "cd /var/www/vhosts/cherrylakepublishing.com/current && backup perform --trigger cherrylake --config_file config/backup.rb --data-path db --log-path log --tmp-path tmp"
rotate_logs: true
rotate_logs_command: "/var/www/vhosts/cherrylakepublishing.com/current/script/logrotate x /var/www/vhosts/cherrylakepublishing.com/current"
clear_wait_a_minute_request_logs: true
implement_price_changes: true
distribute_price_changes: true
