source 'http://rubygems.org'

gem 'rails', '3.0.5'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'rake', '13.0.1'
gem 'backup'
gem 'mysql'
gem 'meta_search'
gem 'formtastic'
gem 'chronic', '= 0.2.3'
gem 'will_paginate', '>= 3.0.3'
gem 'RedCloth', '>= 3.0.4', :require => 'redcloth'
gem 'hpricot'
gem 'fastercsv', '>= 1.2.3'
gem 'rmagick', '>=2.7', :require => 'RMagick'
gem 'pdf-writer', :require => 'pdf/writer'
gem 'newrelic_rpm'
gem 'scribd_fu', '>= 2.0.11'
gem "activemerchant", ">= 1.5.1", :require => "active_merchant"
gem 'whenever'
gem 'onix', :git => 'git://github.com/milkfarm/onix', :branch => 'joseph-refactor'
gem 'daemons'
gem 'vestal_versions', :git => 'git://github.com/adamcooper/vestal_versions'
gem 'delayed_job_active_record'
gem 'exception_notification', :git => 'git://github.com/srejbi/exception_notification', :require => 'exception_notifier'
gem 'preferences', :git => 'git://github.com/srejbi/preferences.git', :branch => 'rails3', :require => 'preferences'
# TODO: Update auto_complete gem to better support Rails 3 (see https://github.com/Agiley/auto_complete)
gem "repeated_auto_complete", :git => 'git://github.com/adamico/auto_complete.git', :require => 'repeated_auto_complete'
gem 'xml-simple'
gem 'libxml-ruby'
gem "wait_a_minute", '>=0.0.4'
gem "transitions", :require => ["transitions", "active_record/transitions"]
gem "parndt-acts_as_tree", ">= 1.2.5", :require => "acts_as_tree"
gem 'isbn_validation'
gem "carrierwave"
gem 'meta-tags', :require => 'meta_tags'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'metric_fu', :require => 'metric_fu'
  # gem 'webrat'
  gem 'rspec'
  gem 'mocha'
end
